### ISSUE TITLE
Dremio fails to start with latest Vertica connector

### ISSUE THREAD

**Issue by jaceksan** [luciodaza/dremio-vertica-connector#6]
Please, check https://community.dremio.com/t/dremio-oss-dockerhub-15-0-fails-to-start/7326/4.

If I could help here in any way, let me know.

**Comment by acrylJonny** [comment]
Please have a look at https://github.com/dremioJonny/dremio-vertica-connector where there are various release of the connector that I've put together

**Comment by jaceksan** [comment]
I downloaded the "jar" from the fork.
Now Dremio does not fail to start, but Vertica data source cannot be registered, Vertica is not in the list of supported data sources in UI and when I try to register it through API, it fails with the following error:
```
ERROR   : DataSourceCreatorDremio : 2021-07-30 10:03:51,188 - RestApi.post to http://localhost:9047/api/v3/catalog failed - response_code=400 message=Could not resolve type id 'verticaARP' as a subtype of `com.dremio.exec.catalog.conf.ConnectionConf<java.lang.Object,java.lang.Object>`: known type ids = [ACCELERATION, ADL, AMAZONELASTIC, AWSGLUE, AZURE_STORAGE, ELASTIC, HDFS, HIVE, HIVE3, HOME, INFORMATION_SCHEMA, INTERNAL, MISSING, MONGO, MSSQL, MYSQL, NAS, ORACLE, PDFS, POSTGRES, REDSHIFT, S3, SNOWFLAKE, SYS] (for POJO property 'config')
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 210]
```

I start Dremio using the following docker-compose, injecting Vertica ARP and JDBC driver:
```
services:
  dremio:
    image: dremio/dremio-oss:17.0.0
    ports:
      - '9047:9047'
      - '31011:31010'
      - '45678:45678'
    volumes:
      # DB drivers
      - ./db-drivers/VERTICA/vertica-jdbc-10.0.1-2.jar:/opt/dremio/jars/3rdparty/vertica-jdbc-10.0.1-2.jar
      # DB plugins
      - ./db-drivers/DREMIO/dremio-verticaarp-plugin.jar:/opt/dremio/jars/dremio-verticaarp-plugin.jar
      # DATA volume
      - dremio-data:/opt/dremio/data

volumes:
  dremio-data:
```
